[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]] #   Include nativefs module
[patches.module]
source = 'nativefs.lua'
before = 'main.lua'
name = 'nativefs'

[[patches]] #   Patch SaveState to main
[patches.copy]
target = "main.lua"
position = "append"
sources = ["SaveState.lua"]

[[patches]] #   Initialize SaveState
[patches.pattern]
target = "game.lua"
pattern = "self:load_profile(G.SETTINGS.profile or 1)"
position = "after"
payload = "initSaveState()"
match_indent = true
overwrite = false

[[patches]] # Inject key press handler
[patches.pattern]
target = "engine/controller.lua"
pattern = "if self.text_input_hook then"
position = "before"
payload = "SaveState.key_press_update(key)"
match_indent = true
overwrite = false
